spring:
  application:
    name: Task-management-system
  datasource:
    url: jdbc:postgresql://localhost:5432/task-management-system
    username: Smertex
    password: Xz1g3n41g4j2F4vbsyEbgbmSER4IEHsdf3h
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
  liquibase:
    enabled: true
  config:
    import: classpath:jwt.yml,classpath:server.yml